aggregating:
  build: aggregating/build/docker
  links:
    - zookeeper:zk
    - rabbitmq
    - configserver
  environment:
    RABBIT_HOST: rabbitmq
    spring.zipkin.enabled: 'false'
    spring.profiles.active: deps
    spring.cloud.config.uri: http://configserver:8888
  command: --spring.cloud.zookeeper.connectString=zk:2181
  ports:
    - 9992:9992

maturing:
  build: maturing/build/docker
  links:
    - zookeeper:zk
    - rabbitmq
    - configserver
  environment:
    RABBIT_HOST: rabbitmq
    spring.zipkin.enabled: 'false'
    spring.profiles.active: deps
    spring.cloud.config.uri: http://configserver:8888
  command: --spring.cloud.zookeeper.connectString=zk:2181
  ports:
    - 9993:9993

bottling:
  build: bottling/build/docker
  links:
    - zookeeper:zk
    - rabbitmq
    - configserver
  environment:
    RABBIT_HOST: rabbitmq
    spring.zipkin.enabled: 'false'
    spring.profiles.active: deps
    spring.cloud.config.uri: http://configserver:8888
  command: --spring.cloud.zookeeper.connectString=zk:2181
  ports:
    - 9994:9994

presenting:
  build: presenting/build/docker
  links:
    - zookeeper:zk
    - rabbitmq
    - configserver
  environment:
    RABBIT_HOST: rabbitmq
    spring.zipkin.enabled: 'false'
    spring.profiles.active: deps
    spring.cloud.config.uri: http://configserver:8888
  command: --spring.cloud.zookeeper.connectString=zk:2181
  ports:
    - 9991:9991

zuul:
  build: zuul/build/docker
  links:
    - zookeeper:zk
    - rabbitmq
    - configserver
  environment:
    RABBIT_HOST: rabbitmq
    spring.zipkin.enabled: 'false'
    spring.profiles.active: deps
    spring.cloud.config.uri: http://configserver:8888
  command: --spring.cloud.zookeeper.connectString=zk:2181
  ports:
    - 9995:9995

ingredients:
  build: ingredients/build/docker
  links:
    - zookeeper:zk
    - rabbitmq
    - configserver
  environment:
    RABBIT_HOST: rabbitmq
    spring.zipkin.enabled: 'false'
    spring.profiles.active: deps
    spring.cloud.config.uri: http://configserver:8888
  command: --spring.cloud.zookeeper.connectString=zk:2181
  ports:
    - 9996:9996

reporting:
  build: reporting/build/docker
  links:
    - zookeeper:zk
    - rabbitmq
    - configserver
  environment:
    RABBIT_HOST: rabbitmq
    spring.zipkin.enabled: 'false'
    spring.profiles.active: deps
    spring.cloud.config.uri: http://configserver:8888
  command: --spring.cloud.zookeeper.connectString=zk:2181
  ports:
    - 9997:9997

configserver:
  build: config-server/build/docker
  ports:
    - 8888:8888

zookeeper:
  image: jplock/zookeeper
  expose:
    - 2181

rabbitmq:
  image: rabbitmq:management
  expose:
    - 5672
    - 15672
