discovery:
  image: jplock/zookeeper
  ports:
    - 2181:2181

web:
  image: openzipkin/zipkin-web:1.30.0
  environment:
    # Remove TRANSPORT_TYPE to disable tracing
    - TRANSPORT_TYPE=http
  ports:
    - 8080:8080
    - 9990:9990

rabbitmq:
  image: rabbitmq:management
  ports:
    - 5672:5672
    - 15672:15672