logging:
  pattern:
    level: '[trace=%X{X-Trace-Id:-},span=%X{X-Span-Id:-}] %5p'

logging.file: zuul.log

server:
  port: 9993

spring.rabbitmq.host: ${RABBIT_HOST:localhost}

# TODO: Not working?
#zuul.route.ingredients: /

zuul:
  ignoredPatterns: /health
  ignoredServices: '*'
  routes:
    brewing: /**

hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000