spring.application.name: ebedded-zookeeper

logging:
  pattern:
    level: '%clr([trace=%X{X-Trace-Id:-},span=%X{X-Span-Id:-}]){yellow} %5p'

server:
  port: 0

logging.file: build/log/application.log